repos:
-   repo: https://github.com/ambv/black
    rev: 21.7b0
    hooks:
    - id: black
      args:
        - --line-length=80
#-   repo: https://github.com/pre-commit/mirrors-isort
#    rev: v5.9.2  # Use the revision sha / tag you want to point at
#    hooks:
#    -   id: isort
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    - id: flake8
      args: #['--config=./setup.cfg']
        - "--max-line-length=80"
        - "--ignore=E203,E266,E501,W503"
        - "--max-line-length=80"
        - "--max-complexity=18"
        - "--select=B,C,E,F,W,T4"
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.910'  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
        args: [--no-strict-optional, --ignore-missing-imports]
    # local stuff
-   repo: local
    hooks:
    -   id: run-tests
        name: run tests
        entry: pytest tests
        stages: [push]
        language: python
        additional_dependencies: [pre-commit, pytest]
        always_run: true
        pass_filenames: false
    -   id: run-sphinx
        name: run sphinx
        entry: sphinx-apidoc -o docs .
        stages: [push]
        language: python
        additional_dependencies: [sphinx]
        always_run: true
